name: golangci-lint
on:
  push:
    tags:
      - v*
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.33
          args: --config=.golangci.yml
